repos:
  - repo: https://github.com/timothycrosley/isort
    rev: 5.9.0
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 21.7b0
    hooks:
      - id: black

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: debug-statements
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-builtin-literals
      - id: end-of-file-fixer
      - id: check-ast
      - id: check-docstring-first
      - id: requirements-txt-fixer

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy

  - repo: https://github.com/PyCQA/bandit
    rev: "1.7.0"
    hooks:
      - id: bandit
