name: Function Action OIDC
description: Deploy a Cognite Function with schedules using OIDC
inputs:
    deployment_client_secret:
        description: Client secret to be used for deployment of the function.
        required: true
    deployment_client_id:
        description: Client ID to be used for deployment of the function.
        required: true
    deployment_tenant_id:
        description: Tenant ID to be used for deployment of the function.
        required: true
    schedules_client_secret:
        description: |
            If function is to be run with schedules, this is the client secret
            to be used at runtime. Not providing this while also passing schedules
            will cause an error to be raised.
        required: false
    schedules_client_id:
        description: |
            If function is to be run with schedules, this is the client ID
            to be used at runtime. Not providing this while also passing schedules
            will cause an error to be raised.
        required: false
    schedules_tenant_id:
        description: |
            If function is to be run with schedules, this is the tenant ID
            to be used at runtime. Not providing this while also passing schedules
            will cause an error to be raised.
        required: false
    cdf_project:
        description: The name of your CDF project.
        required: true
    cdf_cluster:
        description: The cluster your customer's CDF project lives in, like 'westeurope-1' or 'greenfield'.
        required: true
    function_external_id:
        description: |
            External ID and name of function. Must be unique within the CDF project as this action
            always overwrites existing.
        required: true
    function_folder:
        description: Path to the folder where the source code for the function(s) can be found.
        required: false
    function_file:
        description: Name of function file inside function folder, for instance, handler.py.
        required: false
    function_secrets:
        description: Base64 encoded string of secrets in JSON format. See README/secrets.
        required: false
    function_deploy_timeout:
        description: Set the timeout limit in seconds for function deployment. Once reached, deployment is cancelled.
        required: false
    schedule_file:
        description: |
            Relative path and name from (function_folder) of the file with schedules to be attached.
            Not passing this parameter -> no schedules will be attached. If the passed file does not
            exist, a warning will be issued, and no schedules will be attached. On all deployments,
            all existing schedules are deleted (and recreated if there are any)! Note: Requires
            'schedules_client_secret', 'schedules_tenant_id' and 'schedules_client_id' to be passed!
        required: false
    data_set_id:
        description: Data set ID to use for the file uploaded to CDF (the function-associated file, i.e. the zipped code folder)
        required: false
    common_folder:
        description: |
            Directory which contains code used by multiple functions. If not specified, will default
            to 'common' (if it exists).
        required: false
    remove_only:
        description: |
            Short-cut that ONLY removes the function (and all schedules linked) before quitting. Only
            requires deployment credentials, 'cdf_project' and 'function_external_id' to be passed.
        required: false
    post_deploy_cleanup:
        description: |
            If true (the default), the function zip-file uploaded to CDF Files will be
            deleted after the Function has been successfully created.
        required: false
    cpu:
        description: 'Set number of CPU cores per function, e.g. 0.5. NB: Ignored for CDF projects on Azure!'
        required: false
    memory:
        description: 'Set memory per function measured in GB, e.g. 0.8. NB: Ignored for CDF projects on Azure!'
        required: false
    owner:
        description: Set owner of a function, e.g. "My Client".
        required: false
    description:
        description: Set description field of a function, e.g. "This does X for Y if Z".
        required: false
outputs:
    function_external_id:  # id of output
        description: The external ID of the function.
runs:
    using: docker
    image: Dockerfile
