name: Build PR

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout code

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip poetry
        poetry config virtualenvs.create false
        poetry install

    - uses: pre-commit/action@v3
      name: Validate code changes using Pre-Commit
